:toc:
:toc-placement!:

= PrEpS (**Pr**olog/**Ep**ilog for **S**lurm)

toc::[]

== About the Project

PrEpS (**Pr**olog/**Ep**ilog for **S**lurm) is a comprehensive but extensible framework for performing Prolog/Epilog execution inside the Slurm workload scheduler.

Reference documentation for the Slurm Prolog/Epilog mechanism is available here:
https://slurm.schedmd.com/prolog_epilog.html[SchedMD: Prolog / Epilog]

The various Prolog/Epilog mechanisms are summarized in the table below:

|===
|Stage|Slurm Context|Configuration Parameter|Location|User

|Slurm Controller Prolog
|`prolog_slurmctld`
|`PrologSlurmctld`
|Head Node
|SlurmctldUser (`slurm`)

|Slurm Controller Epilog
|`epilog_slurmctld`
|`EpilogSlurmctld`
|Head Node
|SlurmctldUser (`slurm`)

|Slurm Prolog
|`prolog_slurmd`
|`Prolog`
|Compute Node
|SlurmdUser (`root`)

|Slurm Epilog
|`epilog_slurmd`
|`Epilog`
|Compute Node
|SlurmdUser (`root`)

|srun Prolog
|`prolog_srun`
|`SrunProlog` +
(`srun --prolog`)
|srun Invocation Node
|srun Invocation User

|srun Epilog
|`epilog_srun`
|`SrunEpilog` +
(`srun --epilog`)
|srun Invocation Node
|srun Invocation User

|Task Prolog
|`prolog_task`
|`TaskProlog` +
(`srun --task-prolog`)
|Compute Node
|srun Invocation User

|Task Epilog
|`epilog_task`
|`TaskEpilog` +
(`srun --task-epilog`)
|Compute Node
|srun Invocation User
|===

== Software Architecture

=== Scripts

PrEpS main script is located in:
----
PREFIX/preps/bin/preps
----

This script is a single entry point which takes care of calling the proper prolog/epilog script depending on the actual Slurm context:

|===
|Stage|Slurm Context|Script

|Slurm Controller Prolog
|`prolog_slurmctld`
|`PREFIX/preps/bin/preps.prolog_slurmctld`

|Slurm Controller Epilog
|`epilog_slurmctld`
|`PREFIX/preps/bin/preps.epilog_slurmctld`

|Slurm Prolog
|`prolog_slurmd`
|`PREFIX/preps/bin/preps.prolog_slurmd`

|Slurm Epilog
|`epilog_slurmd`
|`PREFIX/preps/bin/preps.epilog_slurmd`

|srun Prolog
|`prolog_srun`
|`PREFIX/preps/bin/preps.prolog_srun`

|srun Epilog
|`epilog_srun`
|`PREFIX/preps/bin/preps.epilog_srun`

|Task Prolog
|`prolog_task`
|`PREFIX/preps/bin/preps.prolog_task`

|Task Epilog
|`epilog_task`
|`PREFIX/preps/bin/preps.epilog_task`
|===

=== Library

==== Packages

PrEpS is divided into several distinct, complementary packages:

|===
|Package |Purpose

|CPU |Manage CPU settings
|Filesystems |Manage filesystems
|Memory |Manage system memory
|NVIDIA |Manage NVIDIA GPU configuration
|Operating System |Manage Operating System components
|Slurm |Manage Slurm-internal operations
|systemd |Manage systemd units
|Transparent Huge Pages |Manage Transparent Huge Pages (THP) configuration
|tuned |Manage tuned profiles
|===

==== Modules

Each PrEpS package is divided into several distinct modules.

===== CPU

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::cpu::set_boost`
|`{0 \| 1}`
|Set CPU boost (Intel Turbo Boost / AMD Core Performance Boost)

|`preps::cpu::set_frequency_min_max`
|`FREQ_MIN:FREQ_MAX`
|Set CPU frequency Min./Max.

|`preps::cpu::set_frequency`
|`FREQ`
|Set CPU frequency

|`preps::cpu::set_governor`
|`GOVERNOR`
|Set CPU governor

|`preps::cpu::set_power_capping`
|`POWER_CAP`
|Set CPU power capping
|===

===== Filesystems

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::fs::check_mountpoints`
|`MOUNTPOINT[,MOUNTPOINT]`
|Check mountpoints

|`preps::fs::cleanup_tmpdirs`
|`TMPDIR[,TMPDIR]`
|Cleanup temporary directories
|===

===== Kernel

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::kernel::set_kernel_parameters`
|`KEY=VALUE[,KEY=VALUE]`
|Set Kernel Parameters
|===

===== Memory

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::memory::cleanup_ipc`
|-
|Cleanup existing Inter-Process Communications (IPC)

|`preps::memory::cleanup_memory_caches`
|`{1: pagecache \| 2: dentries + inodes \| 3: pagecache + dentries + inodes}`
|Cleanup memory caches

|`preps::memory::cleanup_shared_memory_segments`
|-
|Cleanup residual shared memory segments

|`preps::memory::compact_memory`
|-
|Compact memory

|`preps::memory::set_numa_balancing`
|`{0 \| 1}`
|Set NUMA balancing

|`preps::memory::set_stat_interval`
|`INTERVAL`
|Set Virtual Memory statistics interval (in seconds)
|===

===== NVIDIA

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::nvidia::check_pending_retirements`
|-
|Check pending retirements

|`preps::nvidia::check_residual_user_processes`
|-
|Check residual user processes

|`preps::nvidia::cleanup_mps_processes`
|-
|Cleanup residual MPS processes

|`preps::nvidia::reset_applications_clocks`
|-
|Reset applications clocks

|`preps::nvidia::run_dcgm_diag`
|`{1 \| 2 \| 3}`
|Run DCGM diagnostic with specified level

|`preps::nvidia::set_applications_clocks`
|`MEMORY,GRAPHICS`
|Set applications clocks

|`preps::nvidia::set_persistence_mode`
|`{0 \| 1}`
|Set persistence mode

|`preps::nvidia::set_power_limit`
|`POWER_LIMIT`
|Set power limit

|`preps::nvidia::set_vboost_slider`
|`{0 \| 1 \| 2 \| 3 \| 4}`
|Set vboost Slider
|===

===== Operating System

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::os::check_residual_user_processes`
|-
|Check residual user processes

|`preps::os::cleanup_residual_user_processes`
|-
|Cleanup residual user processes

|`preps::os::set_user_limits`
|`OPTION=VALUE[,OPTION=VALUE]`
|Set user limits
|===

===== Slurm

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::slurm::archive_job`
|-
|Archive job configuration environment

|`preps::slurm::run_nhc`
|-
|Run NHC
|===

===== systemd

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::systemd::restart_systemd_unit`
|`UNIT` +
`MAX_ACTIVE_TIME_IN_SECONDS`
|Restart systemd unit if active time is above specified threshold

|`preps::systemd::start_failed_systemd_units`
|-
|Start failed systemd units

|`preps::systemd::start_systemd_units`
|`UNIT[,UNIT]`
|Start systemd units

|`preps::systemd::stop_systemd_units`
|`UNIT[,UNIT]`
|Stop systemd units
|===

===== Transparent Huge Pages (THP)

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::thp::set_thp`
|`{always \| madvise \| never}`
|Set Transparent Huge Pages (THP) mode

|`preps::thp::set_thp_shmem`
|`{always \| deny \| force \| madvise \| never}`
|Set Transparent Huge Pages for SHMEM (THP SHMEM) mode
|===

===== tuned

The package offers the following modules:

[cols="1,1,2",options="header",width="100%"]
|===
|Function Name|Arguments|Purpose

|`preps::tuned::enable_profile`
|`PROFILE`
|Apply tuned profile
|===

== Getting Started

=== Prerequisites

* Functional Slurm workload manager

=== Installation

* Clone Git repository:
+
----
git clone https://github.com/AG-BDS-HPC-DELIVERY/PrEpS/preps.git
----
* Grant proper access rights to the PrEpS directory tree:
+
----
chmod --recursive g=u,g-w,o=g PREFIX/preps
----
* Grant executive access rights to the PrEpS binary:
+
----
chmod a+x PREFIX/preps/bin/preps*
----

=== Configuration

* Define PrEpS executable binary as the target for Prolog/Epilog inside Slurm configuration file `slurm.conf`:
+
----
################################################
#               EPILOG & PROLOG                #
################################################
Epilog=PREFIX/preps/bin/preps
Prolog=PREFIX/preps/bin/preps
----
+
[NOTE]
====
The PrEpS installation directory must be located on a shared filesystem in order to be accessible from every compute node.
====
* Launch Slurm reconfiguration:
+
----
scontrol reconfig
----
* Check that the Prolog/Epilog are properly configured:
+
----
scontrol show config  | awk '/^Epilog\s+=/ || /^Prolog\s+=/'
----
* Build associated Prolog/Epilog scripts by populating files with requested function calls:
+
Example: `preps.prolog_slurmd` Script for Slurm Prolog:
+
----
#!/usr/bin/env bash

preps::nvidia::set_power_limit "${NVIDIA_POWER_LIMIT:-680}"
preps::nvidia::set_vboost_slider "${NVIDIA_VBOOST_SLIDER:-0}"
preps::thp::set_thp "${THP:-always}"

----
* Setup optional override of predefined settings whenever required using the following notation as arguments to the function calls:
+
----
preps::nvidia::set_power_limit "${NVIDIA_POWER_LIMIT:-680}"
----
+
Explanation: Default power limit value is 680, but this value can be overriden by the user on a per-job basis.
+
cf. Section: <<Overrides>>

== Usage

=== Logging

The log level is defined according to the following elements **in decreasing level of priority**:

* Value from the `LOG_LEVEL` environment variable (cf. Section: <<Overrides>>) -> Scope: Job-specific.
* Value from the `-log-level` argument to the PrEpS executable -> Scope: Prolog/Epilog-specific
* Default value inside the PrEpS executable -> Scope: Global.
+
NOTE: Default log level is set to `ERROR` in order to minimize the size of the logfile.

The execution of Prolog/Epilog is logged into the following files:
----
<PREFIX>/preps/var/log/preps.<DD>.log
----

Log file records are made of the following fields:

[cols="1,2",options="header",width="100%"]
|===
|Field Name|Purpose

|Timestamp
|Date and time of the event

|Slurm Job ID
|Slurm ID of the job

|Slurm User Name
|Name of the submission user

|Hostname
|Name of the compute node

|Slurm Context
|Prolog/Epilog context

|Log Level
|Log level of the associated message: Trace, Debugging, Information, Warning, Error, Critical

|Message
|Content of the message
|===


Log File Example::

----
2025-06-27 16:01:19 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Set CPU Governor: [performance]
2025-06-27 16:01:19 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Set CPU Frequency Limits: [81000]-[3321000] ( Hardware Limits: [81000]-[3321000] )
2025-06-27 16:01:19 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | No Residual User Process Found
2025-06-27 16:01:20 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Set Applications Clocks: [2619,1980|2619,1980|2619,1980|2619,1980]
2025-06-27 16:01:20 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Set Video Boost Slider: [0|0|0|0]
2025-06-27 16:01:20 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Set Transparent Huge Pages (THP): [[always] madvise never]
2025-06-27 16:01:20 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Set Kernel Parameter: [kernel.kptr_restrict] to Value: [0]
2025-06-27 16:01:20 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Set Kernel Parameter: [kernel.perf_event_paranoid] to Value: [-1]
2025-06-27 16:01:20 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Set Statistics Interval: [120]
2025-06-27 16:01:20 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Dropped Memory Caches
2025-06-27 16:01:20 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | Compacted Memory
2025-06-27 16:01:20 +02:00 |    61452 | tallet1         | jpbo-123-01     | prolog_slurmd        | INFO  | PrEpS Execution Time (ms): [1630]
2025-06-27 16:01:32 +02:00 |    61452 | tallet1         | jpbo-123-01     | epilog_slurmd        | INFO  | Executed NHC Successfully
2025-06-27 16:01:33 +02:00 |    61452 | tallet1         | jpbo-123-01     | epilog_slurmd        | INFO  | Set Kernel Parameter: [kernel.kptr_restrict] to Value: [1]
2025-06-27 16:01:33 +02:00 |    61452 | tallet1         | jpbo-123-01     | epilog_slurmd        | INFO  | Set Kernel Parameter: [kernel.perf_event_paranoid] to Value: [2]
2025-06-27 16:01:33 +02:00 |    61452 | tallet1         | jpbo-123-01     | epilog_slurmd        | INFO  | Dropped Memory Caches
2025-06-27 16:01:33 +02:00 |    61452 | tallet1         | jpbo-123-01     | epilog_slurmd        | INFO  | PrEpS Execution Time (ms): [1994]
----

=== Overrides

Overrides are designed to allow regular users to alter the configuration of the compute nodes at submission time, with no need to be granted sudo rights.

Overrides rely on environment variables holding user-specific values.

==== Passing Variables to the Prolog/Epilog

The Prolog/Epilog environment **does not** inherit from the current user environment at submission time.

Therefore, in order to pass environment variables to the Prolog/Epilog, it is required to use the `--comment` directive of the `sbatch` command in either of the following two ways:

* As a direct argument to the `sbatch` command itself:
+
----
sbatch --comment "NVIDIA_POWER_LIMIT=680,680" ...
----
* As an explicit directive inside the job submission file:
+
----
#SBATCH --comment="NVIDIA_POWER_LIMIT=680,680"
----

[NOTE]
====
Multiple overrides can be specified as a semi-colon separated list:
----
--comment="VARIABLE=VALUE[;VARIABLE=VALUE]"
----
Example:
----
--comment="NVIDIA_POWER_LIMIT=680,680;NVIDIA_VBOOST_SLIDER=1"
----
====

==== Existing Overrides

[cols="1,2,2",options="header",width="100%"]
|===
|Category|Environment Variable Name|Purpose

|PrEpS
|`PREPS_LOG_LEVEL={TRACE \| DEBUG \| INFO \| WARN \| ERROR \| FATAL}`
|Job-specific log level

|
|`PREPS_SKIP_PROLOG_SLURMD={no \| yes}`
|Skip execution of Slurmd Prolog

|CPU
|`CPU_FREQUENCY_MAX=FREQUENCY`
|CPU frequency max. (Unit: KHz)

|
|`CPU_FREQUENCY_MIN=FREQUENCY`
|CPU frequency min. (Unit: KHz)

|
|`CPU_GOVERNOR=GOVERNOR`
|CPU governor

|
|`CPU_POWER_CAP=CAP`
|CPU power cap (Unit: μW)

|Kernel
|`KERNEL_PARAMETERS=KEY=VALUE[,KEY=VALUE]`
|Extra kernel parameters

|NVIDIA
|`NVIDIA_APPLICATIONS_CLOCKS=MEMORY,GRAPHICS`
|Applications clocks (Unit: MHz)

|
|`NVIDIA_POWER_LIMIT=GPU,MODULE`
|Power limit of the CG GPU/Module devices (Unit: W)

|
|`NVIDIA_VBOOST_SLIDER={0 \| 1 \| 2 \| 3 \| 4}`
|Video Boost Slider

|THP
|`THP={always \| madvise \| never}`
|Configuration of Transparent Huge Pages (THP)

|
|`THP_SHMEM={advise \| always \| deny \| force \| never}`
|Configuration of Transparent Huge Pages (THP) for SHMEM
|===

[NOTE]
====
In order for overrides to be actually enabled, the related environment variables need to be specified as part of the arguments of the related functions.
Example:
----
preps::nvidia::set_power_limit "${NVIDIA_POWER_LIMIT:-680}"
preps::nvidia::set_vboost_slider "${NVIDIA_VBOOST_SLIDER:-0}"
----
====
